### PR TITLE
remove default timezone in vimbtool

### LINKED ISSUE #186: wrong time zone when using vimbtool
When executing "vimbtool.php -a mailbox.cli-get-sizes", time zone in DB columns "size_at" is not considered correctly. So the info in GUI is wrong, too.
For example: `2016-04-20 11:00:00` should be `2016-04-20 12:00:00`
The command `php -i`, `/usr/bin/env php -i` and the phpinfo page show the correct time zone, so the `php.ini` files are set correct.

### PR DESCRIPTION
**Pull request by Phiber2000**
Default timezone parameter in vimbtool always overwrote CLIs php.ini setting to "Europe/Dublin".
This fixes #186.

### CODE REVIEW

**Comment by Phiber2000** [comment]
Still no pull or comment!?
Because it directly has impact on "vimbtool.php", it's no bagatelle...

**Comment by barryo** [comment]
How about framing like this? - 

https://github.com/yiisoft/yii2/commit/810d232ee6717f14f5ecfc4b7b7486ac4d199f26

**Comment by Phiber2000** [comment]
Good idea! But (as far as I know) if no time zone is set in ini, the local time zone is used when creating a DateTime instance without parameters. Framing example would overwrite this behavior.

The questing is: Is there a reason to set another default than the local time zone?
If there really is a reason, wouldn't it be better to overwrite this system wide setting by using a ViMbAdmin wide configuration parameter?

**Comment by PhrozenByte** [comment]
Simply use `date_default_timezone_set(@date_default_timezone_get());` to suppress the warning about a unset timezone.

**Comment by Phiber2000** [comment]
@PhrozenByte I'm using PHP 5.6.20 and don't get any warnings. But if you get one: Why should we suppress a warning remembering the admin to set a possibly missing config parameter in cli-ini? When value is not set, nothing bad happens - local system time is used without any problems.

I would modify the commit/PR but I can't see a reason to set change the default time zone given by the "normal" usage of the php functions at all. Maybe you could give me a hint!?

**Comment by PhrozenByte** [comment]
Please refer to the docs @Phiber2000:

> Since PHP 5.1.0 (when the date/time functions were rewritten), every call to a date/time function will generate a E_NOTICE if the timezone isn't valid, and/or a E_WARNING message if using the system settings or the TZ environment variable. 

Without a properly set timezone in your `php.ini` (what is quite common), ViMbAdmin blows up with a `E_NOTICE` or `E_WARNING` (see above). That's the reason why you **must** call `date_default_timezone_set()`. Using `date_default_timezone_get()` either returns the timezone PHP was configured to use (`php.ini`), or tries to guess a timezone, or simply returns `UTC`. However, `date_default_timezone_get()` still throws an `E_NOTICE` or `E_WARNING` when it guesses a timezone. Thus you have to suppress this particular warning with `@` - what brings us to `date_default_timezone_set(@date_default_timezone_get());`... With a properly configured timezone in your `php.ini` this line simply does nothing, but prevents ViMbAdmin to blow up otherwise.

**Comment by Phiber2000** [comment]
Docs say: "**Prior** to PHP 5.4.0 only: ... A warning is shown when this stage is reached."
And as I said above: "Why should we suppress a warning remembering the admin to set a possibly missing config parameter?"

If the E_WARNING really carries ViMbAdmin to **malfunction** - which I don't get reproduced here - `date_default_timezone_set(@date_default_timezone_get());` would be a workaround.

But the default time zone is only set in vimbtool.php! Are you sure, this is a problem? Please help me to find out, why!
I removed all PHP time zone settings, restarted the services and don't get **any** warning...

**Comment by PhrozenByte** [comment]
Just read the docs, there is pretty clearly elucidated under which circumstances a `E_WARNING` or `E_NOTICE` is generated.

**Comment by Phiber2000** [comment]
To proof, that I read your post **and** the docs:
> every call to a date/time function:
> E_NOTICE if the timezone isn't valid
> E_WARNING message if using the system settings or the TZ environment variable

But it doesn't blow up anything.

**Comment by Phiber2000** [comment]
Have a look at: https://gist.github.com/Phiber2000/862446158ae4c7fdced935ee2488341e

**Comment by PhrozenByte** [comment]
> Also note that the behavior changed over time and PHP version, so how do you expect to reproduce the behavior of different PHP versions with just one PHP version installed?

**Comment by Phiber2000** [comment]
As I said: "Why should we suppress a warning remembering the admin to set a possibly missing config parameter?"
In all PHP versions the worst thing that could happen is, to get a warning and a UTC time stamp in database.

If you know more specific - please give a reproducable example using PHP >= 5.4.

**Comment by PhrozenByte** [comment]
It's not the purpose of an application like ViMbAdmin to enforce changing *global* configuration parameters. It at most changes them *locally* or works around them. As said, just because it works for you with *just* your PHP version on *just* your platform (e.g. Debian's PHP is patched to likely never issue this `E_WARNING`), you can't assume that it works everywhere else - especially not when the docs explicitly tell you that it **doesn't**. This is a very common problem I've experienced many times on customer platforms. Also don't forget that `vimbtool` usually is run by an cronjob with silenced stdout, so the warning doesn't show up anywhere.

However, I've said everything I wanted to say and don't want to repeat myself a fifth time. This is a decision @barryo has to make, it's just important that he knows that there is a better solution than the one you're suggesting with this PR.

**Comment by Phiber2000** [comment]
You're right with your statement that ViMbAdmin should not enforce changing global configuration parameters.
So **your** answer to one of the very first questions I asked - "If there really is a reason, wouldn't it be better to overwrite this system wide setting by using a ViMbAdmin wide configuration parameter?" - is just: Yes!

That Debians PHPs are patched to never show the warnings explains a lot! (Tried PHP7, too.) Thanks for this info!

**Comment by Phiber2000** [comment]
I changed the PR to use UTC, if none set in CLIs php.ini which will work on any PHP version for sure.
I think, this is the easiest fix.

**Comment by barryo** [comment]
Thanks @Phiber2000  for the PR and @PhrozenByte for the education on this 🍻

**Comment by Phiber2000** [comment]
@PhrozenByte :+1: for the lively discussion.

**Pull request merged**
